# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chaosrings/Desktop/myserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chaosrings/Desktop/myserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chaosrings/Desktop/myserver/CMakeFiles /home/chaosrings/Desktop/myserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chaosrings/Desktop/myserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myserver

# Build rule for target.
myserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myserver
.PHONY : myserver

# fast build rule for target.
myserver/fast:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/build
.PHONY : myserver/fast

src/App/application.o: src/App/application.cpp.o

.PHONY : src/App/application.o

# target to build an object file
src/App/application.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/App/application.cpp.o
.PHONY : src/App/application.cpp.o

src/App/application.i: src/App/application.cpp.i

.PHONY : src/App/application.i

# target to preprocess a source file
src/App/application.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/App/application.cpp.i
.PHONY : src/App/application.cpp.i

src/App/application.s: src/App/application.cpp.s

.PHONY : src/App/application.s

# target to generate assembly for a file
src/App/application.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/App/application.cpp.s
.PHONY : src/App/application.cpp.s

src/Buffer/Buffer.o: src/Buffer/Buffer.cpp.o

.PHONY : src/Buffer/Buffer.o

# target to build an object file
src/Buffer/Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Buffer/Buffer.cpp.o
.PHONY : src/Buffer/Buffer.cpp.o

src/Buffer/Buffer.i: src/Buffer/Buffer.cpp.i

.PHONY : src/Buffer/Buffer.i

# target to preprocess a source file
src/Buffer/Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Buffer/Buffer.cpp.i
.PHONY : src/Buffer/Buffer.cpp.i

src/Buffer/Buffer.s: src/Buffer/Buffer.cpp.s

.PHONY : src/Buffer/Buffer.s

# target to generate assembly for a file
src/Buffer/Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Buffer/Buffer.cpp.s
.PHONY : src/Buffer/Buffer.cpp.s

src/DataVariant/FormUrlencoded.o: src/DataVariant/FormUrlencoded.cpp.o

.PHONY : src/DataVariant/FormUrlencoded.o

# target to build an object file
src/DataVariant/FormUrlencoded.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/FormUrlencoded.cpp.o
.PHONY : src/DataVariant/FormUrlencoded.cpp.o

src/DataVariant/FormUrlencoded.i: src/DataVariant/FormUrlencoded.cpp.i

.PHONY : src/DataVariant/FormUrlencoded.i

# target to preprocess a source file
src/DataVariant/FormUrlencoded.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/FormUrlencoded.cpp.i
.PHONY : src/DataVariant/FormUrlencoded.cpp.i

src/DataVariant/FormUrlencoded.s: src/DataVariant/FormUrlencoded.cpp.s

.PHONY : src/DataVariant/FormUrlencoded.s

# target to generate assembly for a file
src/DataVariant/FormUrlencoded.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/FormUrlencoded.cpp.s
.PHONY : src/DataVariant/FormUrlencoded.cpp.s

src/DataVariant/TextPlain.o: src/DataVariant/TextPlain.cpp.o

.PHONY : src/DataVariant/TextPlain.o

# target to build an object file
src/DataVariant/TextPlain.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/TextPlain.cpp.o
.PHONY : src/DataVariant/TextPlain.cpp.o

src/DataVariant/TextPlain.i: src/DataVariant/TextPlain.cpp.i

.PHONY : src/DataVariant/TextPlain.i

# target to preprocess a source file
src/DataVariant/TextPlain.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/TextPlain.cpp.i
.PHONY : src/DataVariant/TextPlain.cpp.i

src/DataVariant/TextPlain.s: src/DataVariant/TextPlain.cpp.s

.PHONY : src/DataVariant/TextPlain.s

# target to generate assembly for a file
src/DataVariant/TextPlain.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/TextPlain.cpp.s
.PHONY : src/DataVariant/TextPlain.cpp.s

src/Reactor/Channel.o: src/Reactor/Channel.cpp.o

.PHONY : src/Reactor/Channel.o

# target to build an object file
src/Reactor/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/Channel.cpp.o
.PHONY : src/Reactor/Channel.cpp.o

src/Reactor/Channel.i: src/Reactor/Channel.cpp.i

.PHONY : src/Reactor/Channel.i

# target to preprocess a source file
src/Reactor/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/Channel.cpp.i
.PHONY : src/Reactor/Channel.cpp.i

src/Reactor/Channel.s: src/Reactor/Channel.cpp.s

.PHONY : src/Reactor/Channel.s

# target to generate assembly for a file
src/Reactor/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/Channel.cpp.s
.PHONY : src/Reactor/Channel.cpp.s

src/Reactor/Epoll.o: src/Reactor/Epoll.cpp.o

.PHONY : src/Reactor/Epoll.o

# target to build an object file
src/Reactor/Epoll.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/Epoll.cpp.o
.PHONY : src/Reactor/Epoll.cpp.o

src/Reactor/Epoll.i: src/Reactor/Epoll.cpp.i

.PHONY : src/Reactor/Epoll.i

# target to preprocess a source file
src/Reactor/Epoll.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/Epoll.cpp.i
.PHONY : src/Reactor/Epoll.cpp.i

src/Reactor/Epoll.s: src/Reactor/Epoll.cpp.s

.PHONY : src/Reactor/Epoll.s

# target to generate assembly for a file
src/Reactor/Epoll.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/Epoll.cpp.s
.PHONY : src/Reactor/Epoll.cpp.s

src/Reactor/EventLoop.o: src/Reactor/EventLoop.cpp.o

.PHONY : src/Reactor/EventLoop.o

# target to build an object file
src/Reactor/EventLoop.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoop.cpp.o
.PHONY : src/Reactor/EventLoop.cpp.o

src/Reactor/EventLoop.i: src/Reactor/EventLoop.cpp.i

.PHONY : src/Reactor/EventLoop.i

# target to preprocess a source file
src/Reactor/EventLoop.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoop.cpp.i
.PHONY : src/Reactor/EventLoop.cpp.i

src/Reactor/EventLoop.s: src/Reactor/EventLoop.cpp.s

.PHONY : src/Reactor/EventLoop.s

# target to generate assembly for a file
src/Reactor/EventLoop.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoop.cpp.s
.PHONY : src/Reactor/EventLoop.cpp.s

src/Reactor/EventLoopThread.o: src/Reactor/EventLoopThread.cpp.o

.PHONY : src/Reactor/EventLoopThread.o

# target to build an object file
src/Reactor/EventLoopThread.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoopThread.cpp.o
.PHONY : src/Reactor/EventLoopThread.cpp.o

src/Reactor/EventLoopThread.i: src/Reactor/EventLoopThread.cpp.i

.PHONY : src/Reactor/EventLoopThread.i

# target to preprocess a source file
src/Reactor/EventLoopThread.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoopThread.cpp.i
.PHONY : src/Reactor/EventLoopThread.cpp.i

src/Reactor/EventLoopThread.s: src/Reactor/EventLoopThread.cpp.s

.PHONY : src/Reactor/EventLoopThread.s

# target to generate assembly for a file
src/Reactor/EventLoopThread.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoopThread.cpp.s
.PHONY : src/Reactor/EventLoopThread.cpp.s

src/Reactor/EventLoopThreadPool.o: src/Reactor/EventLoopThreadPool.cpp.o

.PHONY : src/Reactor/EventLoopThreadPool.o

# target to build an object file
src/Reactor/EventLoopThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoopThreadPool.cpp.o
.PHONY : src/Reactor/EventLoopThreadPool.cpp.o

src/Reactor/EventLoopThreadPool.i: src/Reactor/EventLoopThreadPool.cpp.i

.PHONY : src/Reactor/EventLoopThreadPool.i

# target to preprocess a source file
src/Reactor/EventLoopThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoopThreadPool.cpp.i
.PHONY : src/Reactor/EventLoopThreadPool.cpp.i

src/Reactor/EventLoopThreadPool.s: src/Reactor/EventLoopThreadPool.cpp.s

.PHONY : src/Reactor/EventLoopThreadPool.s

# target to generate assembly for a file
src/Reactor/EventLoopThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Reactor/EventLoopThreadPool.cpp.s
.PHONY : src/Reactor/EventLoopThreadPool.cpp.s

src/Server/HttpRequest.o: src/Server/HttpRequest.cpp.o

.PHONY : src/Server/HttpRequest.o

# target to build an object file
src/Server/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpRequest.cpp.o
.PHONY : src/Server/HttpRequest.cpp.o

src/Server/HttpRequest.i: src/Server/HttpRequest.cpp.i

.PHONY : src/Server/HttpRequest.i

# target to preprocess a source file
src/Server/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpRequest.cpp.i
.PHONY : src/Server/HttpRequest.cpp.i

src/Server/HttpRequest.s: src/Server/HttpRequest.cpp.s

.PHONY : src/Server/HttpRequest.s

# target to generate assembly for a file
src/Server/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpRequest.cpp.s
.PHONY : src/Server/HttpRequest.cpp.s

src/Server/HttpResponse.o: src/Server/HttpResponse.cpp.o

.PHONY : src/Server/HttpResponse.o

# target to build an object file
src/Server/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpResponse.cpp.o
.PHONY : src/Server/HttpResponse.cpp.o

src/Server/HttpResponse.i: src/Server/HttpResponse.cpp.i

.PHONY : src/Server/HttpResponse.i

# target to preprocess a source file
src/Server/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpResponse.cpp.i
.PHONY : src/Server/HttpResponse.cpp.i

src/Server/HttpResponse.s: src/Server/HttpResponse.cpp.s

.PHONY : src/Server/HttpResponse.s

# target to generate assembly for a file
src/Server/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpResponse.cpp.s
.PHONY : src/Server/HttpResponse.cpp.s

src/Server/HttpServer.o: src/Server/HttpServer.cpp.o

.PHONY : src/Server/HttpServer.o

# target to build an object file
src/Server/HttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpServer.cpp.o
.PHONY : src/Server/HttpServer.cpp.o

src/Server/HttpServer.i: src/Server/HttpServer.cpp.i

.PHONY : src/Server/HttpServer.i

# target to preprocess a source file
src/Server/HttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpServer.cpp.i
.PHONY : src/Server/HttpServer.cpp.i

src/Server/HttpServer.s: src/Server/HttpServer.cpp.s

.PHONY : src/Server/HttpServer.s

# target to generate assembly for a file
src/Server/HttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/HttpServer.cpp.s
.PHONY : src/Server/HttpServer.cpp.s

src/Server/Server.o: src/Server/Server.cpp.o

.PHONY : src/Server/Server.o

# target to build an object file
src/Server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/Server.cpp.o
.PHONY : src/Server/Server.cpp.o

src/Server/Server.i: src/Server/Server.cpp.i

.PHONY : src/Server/Server.i

# target to preprocess a source file
src/Server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/Server.cpp.i
.PHONY : src/Server/Server.cpp.i

src/Server/Server.s: src/Server/Server.cpp.s

.PHONY : src/Server/Server.s

# target to generate assembly for a file
src/Server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/Server.cpp.s
.PHONY : src/Server/Server.cpp.s

src/Socket/Socket.o: src/Socket/Socket.cpp.o

.PHONY : src/Socket/Socket.o

# target to build an object file
src/Socket/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Socket/Socket.cpp.o
.PHONY : src/Socket/Socket.cpp.o

src/Socket/Socket.i: src/Socket/Socket.cpp.i

.PHONY : src/Socket/Socket.i

# target to preprocess a source file
src/Socket/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Socket/Socket.cpp.i
.PHONY : src/Socket/Socket.cpp.i

src/Socket/Socket.s: src/Socket/Socket.cpp.s

.PHONY : src/Socket/Socket.s

# target to generate assembly for a file
src/Socket/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Socket/Socket.cpp.s
.PHONY : src/Socket/Socket.cpp.s

src/Timer/Timer.o: src/Timer/Timer.cpp.o

.PHONY : src/Timer/Timer.o

# target to build an object file
src/Timer/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Timer/Timer.cpp.o
.PHONY : src/Timer/Timer.cpp.o

src/Timer/Timer.i: src/Timer/Timer.cpp.i

.PHONY : src/Timer/Timer.i

# target to preprocess a source file
src/Timer/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Timer/Timer.cpp.i
.PHONY : src/Timer/Timer.cpp.i

src/Timer/Timer.s: src/Timer/Timer.cpp.s

.PHONY : src/Timer/Timer.s

# target to generate assembly for a file
src/Timer/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Timer/Timer.cpp.s
.PHONY : src/Timer/Timer.cpp.s

src/Utils/Utils.o: src/Utils/Utils.cpp.o

.PHONY : src/Utils/Utils.o

# target to build an object file
src/Utils/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Utils/Utils.cpp.o
.PHONY : src/Utils/Utils.cpp.o

src/Utils/Utils.i: src/Utils/Utils.cpp.i

.PHONY : src/Utils/Utils.i

# target to preprocess a source file
src/Utils/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Utils/Utils.cpp.i
.PHONY : src/Utils/Utils.cpp.i

src/Utils/Utils.s: src/Utils/Utils.cpp.s

.PHONY : src/Utils/Utils.s

# target to generate assembly for a file
src/Utils/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Utils/Utils.cpp.s
.PHONY : src/Utils/Utils.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... myserver"
	@echo "... edit_cache"
	@echo "... src/App/application.o"
	@echo "... src/App/application.i"
	@echo "... src/App/application.s"
	@echo "... src/Buffer/Buffer.o"
	@echo "... src/Buffer/Buffer.i"
	@echo "... src/Buffer/Buffer.s"
	@echo "... src/DataVariant/FormUrlencoded.o"
	@echo "... src/DataVariant/FormUrlencoded.i"
	@echo "... src/DataVariant/FormUrlencoded.s"
	@echo "... src/DataVariant/TextPlain.o"
	@echo "... src/DataVariant/TextPlain.i"
	@echo "... src/DataVariant/TextPlain.s"
	@echo "... src/Reactor/Channel.o"
	@echo "... src/Reactor/Channel.i"
	@echo "... src/Reactor/Channel.s"
	@echo "... src/Reactor/Epoll.o"
	@echo "... src/Reactor/Epoll.i"
	@echo "... src/Reactor/Epoll.s"
	@echo "... src/Reactor/EventLoop.o"
	@echo "... src/Reactor/EventLoop.i"
	@echo "... src/Reactor/EventLoop.s"
	@echo "... src/Reactor/EventLoopThread.o"
	@echo "... src/Reactor/EventLoopThread.i"
	@echo "... src/Reactor/EventLoopThread.s"
	@echo "... src/Reactor/EventLoopThreadPool.o"
	@echo "... src/Reactor/EventLoopThreadPool.i"
	@echo "... src/Reactor/EventLoopThreadPool.s"
	@echo "... src/Server/HttpRequest.o"
	@echo "... src/Server/HttpRequest.i"
	@echo "... src/Server/HttpRequest.s"
	@echo "... src/Server/HttpResponse.o"
	@echo "... src/Server/HttpResponse.i"
	@echo "... src/Server/HttpResponse.s"
	@echo "... src/Server/HttpServer.o"
	@echo "... src/Server/HttpServer.i"
	@echo "... src/Server/HttpServer.s"
	@echo "... src/Server/Server.o"
	@echo "... src/Server/Server.i"
	@echo "... src/Server/Server.s"
	@echo "... src/Socket/Socket.o"
	@echo "... src/Socket/Socket.i"
	@echo "... src/Socket/Socket.s"
	@echo "... src/Timer/Timer.o"
	@echo "... src/Timer/Timer.i"
	@echo "... src/Timer/Timer.s"
	@echo "... src/Utils/Utils.o"
	@echo "... src/Utils/Utils.i"
	@echo "... src/Utils/Utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

