# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chaosrings/Desktop/myserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chaosrings/Desktop/myserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chaosrings/Desktop/myserver/CMakeFiles /home/chaosrings/Desktop/myserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chaosrings/Desktop/myserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myserver

# Build rule for target.
myserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myserver
.PHONY : myserver

# fast build rule for target.
myserver/fast:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/build
.PHONY : myserver/fast

src/DataVariant/FormUrlencoded.o: src/DataVariant/FormUrlencoded.cpp.o

.PHONY : src/DataVariant/FormUrlencoded.o

# target to build an object file
src/DataVariant/FormUrlencoded.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/FormUrlencoded.cpp.o
.PHONY : src/DataVariant/FormUrlencoded.cpp.o

src/DataVariant/FormUrlencoded.i: src/DataVariant/FormUrlencoded.cpp.i

.PHONY : src/DataVariant/FormUrlencoded.i

# target to preprocess a source file
src/DataVariant/FormUrlencoded.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/FormUrlencoded.cpp.i
.PHONY : src/DataVariant/FormUrlencoded.cpp.i

src/DataVariant/FormUrlencoded.s: src/DataVariant/FormUrlencoded.cpp.s

.PHONY : src/DataVariant/FormUrlencoded.s

# target to generate assembly for a file
src/DataVariant/FormUrlencoded.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/FormUrlencoded.cpp.s
.PHONY : src/DataVariant/FormUrlencoded.cpp.s

src/DataVariant/TextPlain.o: src/DataVariant/TextPlain.cpp.o

.PHONY : src/DataVariant/TextPlain.o

# target to build an object file
src/DataVariant/TextPlain.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/TextPlain.cpp.o
.PHONY : src/DataVariant/TextPlain.cpp.o

src/DataVariant/TextPlain.i: src/DataVariant/TextPlain.cpp.i

.PHONY : src/DataVariant/TextPlain.i

# target to preprocess a source file
src/DataVariant/TextPlain.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/TextPlain.cpp.i
.PHONY : src/DataVariant/TextPlain.cpp.i

src/DataVariant/TextPlain.s: src/DataVariant/TextPlain.cpp.s

.PHONY : src/DataVariant/TextPlain.s

# target to generate assembly for a file
src/DataVariant/TextPlain.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/DataVariant/TextPlain.cpp.s
.PHONY : src/DataVariant/TextPlain.cpp.s

src/Request/HttpRequest.o: src/Request/HttpRequest.cpp.o

.PHONY : src/Request/HttpRequest.o

# target to build an object file
src/Request/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Request/HttpRequest.cpp.o
.PHONY : src/Request/HttpRequest.cpp.o

src/Request/HttpRequest.i: src/Request/HttpRequest.cpp.i

.PHONY : src/Request/HttpRequest.i

# target to preprocess a source file
src/Request/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Request/HttpRequest.cpp.i
.PHONY : src/Request/HttpRequest.cpp.i

src/Request/HttpRequest.s: src/Request/HttpRequest.cpp.s

.PHONY : src/Request/HttpRequest.s

# target to generate assembly for a file
src/Request/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Request/HttpRequest.cpp.s
.PHONY : src/Request/HttpRequest.cpp.s

src/Resource/Resource.o: src/Resource/Resource.cpp.o

.PHONY : src/Resource/Resource.o

# target to build an object file
src/Resource/Resource.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Resource/Resource.cpp.o
.PHONY : src/Resource/Resource.cpp.o

src/Resource/Resource.i: src/Resource/Resource.cpp.i

.PHONY : src/Resource/Resource.i

# target to preprocess a source file
src/Resource/Resource.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Resource/Resource.cpp.i
.PHONY : src/Resource/Resource.cpp.i

src/Resource/Resource.s: src/Resource/Resource.cpp.s

.PHONY : src/Resource/Resource.s

# target to generate assembly for a file
src/Resource/Resource.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Resource/Resource.cpp.s
.PHONY : src/Resource/Resource.cpp.s

src/Response/HttpResponse.o: src/Response/HttpResponse.cpp.o

.PHONY : src/Response/HttpResponse.o

# target to build an object file
src/Response/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Response/HttpResponse.cpp.o
.PHONY : src/Response/HttpResponse.cpp.o

src/Response/HttpResponse.i: src/Response/HttpResponse.cpp.i

.PHONY : src/Response/HttpResponse.i

# target to preprocess a source file
src/Response/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Response/HttpResponse.cpp.i
.PHONY : src/Response/HttpResponse.cpp.i

src/Response/HttpResponse.s: src/Response/HttpResponse.cpp.s

.PHONY : src/Response/HttpResponse.s

# target to generate assembly for a file
src/Response/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Response/HttpResponse.cpp.s
.PHONY : src/Response/HttpResponse.cpp.s

src/Server/ServeHttp.o: src/Server/ServeHttp.cpp.o

.PHONY : src/Server/ServeHttp.o

# target to build an object file
src/Server/ServeHttp.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/ServeHttp.cpp.o
.PHONY : src/Server/ServeHttp.cpp.o

src/Server/ServeHttp.i: src/Server/ServeHttp.cpp.i

.PHONY : src/Server/ServeHttp.i

# target to preprocess a source file
src/Server/ServeHttp.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/ServeHttp.cpp.i
.PHONY : src/Server/ServeHttp.cpp.i

src/Server/ServeHttp.s: src/Server/ServeHttp.cpp.s

.PHONY : src/Server/ServeHttp.s

# target to generate assembly for a file
src/Server/ServeHttp.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Server/ServeHttp.cpp.s
.PHONY : src/Server/ServeHttp.cpp.s

src/Socket/Socket.o: src/Socket/Socket.cpp.o

.PHONY : src/Socket/Socket.o

# target to build an object file
src/Socket/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Socket/Socket.cpp.o
.PHONY : src/Socket/Socket.cpp.o

src/Socket/Socket.i: src/Socket/Socket.cpp.i

.PHONY : src/Socket/Socket.i

# target to preprocess a source file
src/Socket/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Socket/Socket.cpp.i
.PHONY : src/Socket/Socket.cpp.i

src/Socket/Socket.s: src/Socket/Socket.cpp.s

.PHONY : src/Socket/Socket.s

# target to generate assembly for a file
src/Socket/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/Socket/Socket.cpp.s
.PHONY : src/Socket/Socket.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/myserver.dir/build.make CMakeFiles/myserver.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... myserver"
	@echo "... edit_cache"
	@echo "... src/DataVariant/FormUrlencoded.o"
	@echo "... src/DataVariant/FormUrlencoded.i"
	@echo "... src/DataVariant/FormUrlencoded.s"
	@echo "... src/DataVariant/TextPlain.o"
	@echo "... src/DataVariant/TextPlain.i"
	@echo "... src/DataVariant/TextPlain.s"
	@echo "... src/Request/HttpRequest.o"
	@echo "... src/Request/HttpRequest.i"
	@echo "... src/Request/HttpRequest.s"
	@echo "... src/Resource/Resource.o"
	@echo "... src/Resource/Resource.i"
	@echo "... src/Resource/Resource.s"
	@echo "... src/Response/HttpResponse.o"
	@echo "... src/Response/HttpResponse.i"
	@echo "... src/Response/HttpResponse.s"
	@echo "... src/Server/ServeHttp.o"
	@echo "... src/Server/ServeHttp.i"
	@echo "... src/Server/ServeHttp.s"
	@echo "... src/Socket/Socket.o"
	@echo "... src/Socket/Socket.i"
	@echo "... src/Socket/Socket.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

